config/routes.rb
Rails.application.routes.draw do
  root "properties#index"

  resources :properties
  resources :shots do 
  resources :comments

end


  devise_for :users, controllers: { registrations: "registrations" }
  
  
  
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :shot
    belongs_to :user
end

app/models/property.rb
class Property < ApplicationRecord
    belongs_to :user
    mount_uploader :user_kra, UserKraUploader

end

app/models/shot.rb
class Shot < ApplicationRecord

belongs_to :user
has_many :comments, dependent: :destroy

mount_uploader :user_kra, UserKraUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  
  
 has_many :properties, dependent: :destroy

has_many :comments, dependent: :destroy

has_many :shots, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  
  
  
def create
  @shot = Shot.find(params[:shot_id]) # finds the id for the shot
  @comment = @shot.comments.create(comment_params) # finds the shot and builds a comment on it
  @comment.user_id = current_user.id if current_user # assigns user id to a comment
  @comment.save!
  redirect_to shot_path(@shot)



end
















def destroy
  @shot = Shot.find(params[:shot_id])
  @comment = @shot.comments.find(params[:id])
  @comment.destroy
  redirect_to shot_path(@shot)

end




  private

def comment_params
  params.require(:comment).permit(:name, :response)

end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = current_user.properties.build
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = current_user.properties.build(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:name, :price, :address, :rooms, :bathrooms, :user_kra, :user_kra_cache, :parking_spaces, :details)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end




    def account_update
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)

    end






end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
  before_action :set_shot, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]

  # GET /shots
  # GET /shots.json
  def index
    @shots = Shot.all
  end

  # GET /shots/1
  # GET /shots/1.json
  def show
  end

  # GET /shots/new
  def new
    @shot = current_user.shots.build
  end

  # GET /shots/1/edit
  def edit
  end

  # POST /shots
  # POST /shots.json
  def create
    @shot = current_user.shots.build(shot_params)

    respond_to do |format|
      if @shot.save
        format.html { redirect_to @shot, notice: 'Shot was successfully created.' }
        format.json { render :show, status: :created, location: @shot }
      else
        format.html { render :new }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shots/1
  # PATCH/PUT /shots/1.json
  def update
    respond_to do |format|
      if @shot.update(shot_params)
        format.html { redirect_to @shot, notice: 'Shot was successfully updated.' }
        format.json { render :show, status: :ok, location: @shot }
      else
        format.html { render :edit }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shots/1
  # DELETE /shots/1.json
  def destroy
    @shot.destroy
    respond_to do |format|
      format.html { redirect_to shots_url, notice: 'Shot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shot
      @shot = Shot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shot_params
      params.require(:shot).permit(:title, :description, :user_id, :user_kra)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/views/comments/_comment.html.erb
<div class="user-comment">
    <%= gravatar_image_tag(comment.user.email.gsub("spam", "mdeering"), alt: comment.user.name, gravatar: { size: 48 } ) %>
    <p><%= comment.user.name %></p>
    <p><%= comment.response%></p>
    <p><% if user_signed_in? && (current_user.id == comment.user_id ) %></p>
    <%= link_to "Delete", [comment.shot, comment], method: :delete, data: {confirm: "are you sure ?"}, class: "btn btn-danger"%>
    <%end%>
</div>

app/views/comments/_form.html.erb
<div class="form-comment">
    <h4>Leave a comment</h4>
    <br>
     <%= simple_form_for([@shot, @shot.comments.build]) do |f| %>
        <%= f.input :name %>
        <%= f.input :response %>
        <%= f.button :submit, "Leave a reply", class:"btn btn-success" %>
    <%end%>

</div>

app/views/comments/edit.html.erb
<%= render "comments/form" %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>Dribble</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

<body>
           <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a><%= link_to "Dribble", shots_path, class:"navbar-brand"%></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
            <a><%= link_to "Shots", shots_path, class:"nav-link" %><span class="sr-only">(current)</span></a>
            </li>
            <% if user_signed_in? %>

            <li class="nav-item"  >
            <a><%= link_to "New Shot", new_shot_path, class:"nav-link btn btn-link" %></a>
            </li>
            <li class="nav-item">
            <a ><%= link_to "Logout", destroy_user_session_path, method: :delete, class:"nav-link" %></a>
            </li>
            <li class="nav-item">
            <%= link_to edit_user_registration_path, class:"nav-link" do %>
            <span class="glyphicon glyphicon-user"><%= current_user.name %></span> 
            <%end%>
            </li>
            <li class="nav-item"  >
            <a><%= link_to "New property", new_property_path, class:"nav-link" %></a>
            </li>


            <li class="nav-item"  >
            <a><%= link_to "All properties", root_path, class:"nav-link" %></a>
            </li>
            <% else %>
            <li class="nav-item">
            <a ><%= link_to "Signup", new_user_registration_path, class:"nav-link" %> </a>
            </li>
            <li class="nav-item">
            <a ><%= link_to "Login", new_user_session_path, class:"nav-link " %></a>
            </li>
            <%end%>

            </ul>
            </div>
          </nav>




          <% if user_signed_in? %>
          <div class="alert alert-link" >
            <%= notice %> 
          </div>
  
        <%end%>


  



        <%= yield %>
  
  
  
        <footer> §$&Shai Sterling</footer>

  
  </body>
</html>

app/views/properties/_form.html.erb
<%= simple_form_for (@property), html: { mulitiparts: true } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :rooms %>
    <%= f.input :bathrooms %>
    <%= f.input :price %>
    <%= f.input :parking_spaces %>
    <%= f.input :details %>



    
    <%= f.input :user_kra, label: 'Upload file' %>
    <%= f.hidden_field :user_kra_cache %>
  </div>


  <%= image_tag @property.user_kra_url (:thumb) unless @property.user_kra.blank? %>
  <div class="form-actions">
  <br>

    <%= f.button :submit, class:"btn btn-success" %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<div class="edit">
    <div class="side-bar">
        <ul class="side-links">
        <li><i class="fa fa-home"></i> Dashboard</li>
        <li><i class="fa fa-th-large"></i> Properties</li>
        <li><i class="fa fa-eye"></i> Viewings</li>
        <li><i class="fa fa-users"></i> Customers</li>
        <li><i class="fa fa-line-chart"></I> Reports</li>
        <li>SAVED REPORTS</li>
        <li><i class="fa fa-file"></i> This Month</li>
        <li><i class="fa fa-file"></i> Engagement</li>
        </ul>
    </div>

    <div class="editing-form">
        <h3>Editing Property</h3>
        <br>
        <%= render 'form', property: @property %>
    </div>
</div>

app/views/properties/index.html.erb
<div class="property-back">
      <div class="domain">Domain</div>
      <div class="help">How can we help?</div>
      <div class="hero-info">
        <div class="hero-items"> <img src="/assets/mail.ico" class="mail"><span>Sell my home</span></div>
        <div class="hero-items"><img src="/assets/mail.ico" class="mail"><span>Manage my property</span></div>
        <div class="hero-items"><img src="/assets/mail.ico" class="mail"><span>Other enquiry</span></div>
      </div>

      <div class="star">
        <div class="star-text">
          <h5>Domain Real Estates</h5>
          <p>Teshie-Nungua Estates Number 208, 4th Floor </p>
          <br>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis odit animi hic eum eos laudantium porro perferendis doloremque consequuntur esse magnam quo, qui nesciunt! Quaerat nostrum eum porro id laborum?
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis odit animi hic eum eos laudantium porro perferendis doloremque consequuntur esse magnam quo, qui nesciunt! Quaerat nostrum eum porro id laborum?</p>
          <br>
          <img src="/assets/fb.ico" class="fb"><span><img src="/assets/twitter.ico" class="twitter"></span>
          <div class="info-us">
          <div class="call"><img src="/assets/phone.ico" class="mail"><span>Call us</span></div>
          <div class="email"><img src="/assets/mail.ico" class="mail"><span>Email us</span></div>
          </div>
        </div>
        <div class="star-images"></div>
      </div>
</div>

<div class="properties">
  <% @properties.each do |property| %>
    <div class="property">
      <%= link_to image_tag(property.user_kra.url (:full)), property %>
      <div class="amenities">
        <p><%= property.name.capitalize %></p>
        <p><%= property.address %></p>
        <i class="fa fa-bed"> <%= property.rooms %> </i>
        <i class="fa fa-bath"> <%= property.bathrooms %></i>
      </div>
    </div>
    <% end %>
</div>


<br>

app/views/properties/new.html.erb
<div class="edit">
<div class="side-bar">
    <ul class="side-links">
    <li><i class="fa fa-home"></i> Dashboard</li>
    <li><i class="fa fa-th-large"></i> Properties</li>
    <li><i class="fa fa-eye"></i> Viewings</li>
    <li><i class="fa fa-users"></i> Customers</li>
    <li><i class="fa fa-line-chart"></I> Reports</li>
    <li>SAVED REPORTS</li>
    <li><i class="fa fa-file"></i> This Month</li>
    <li><i class="fa fa-file"></i> Engagement</li>
    </ul>
</div>

<div class="editing-form">
<h3>New Property</h3>

    <%= render 'form', property: @property %>
</div>
</div>

app/views/properties/show.html.erb
<div id="show-background">
  <div class="show-big-img">
    <%= image_tag @property.user_kra_url (:full) unless @property.user_kra.blank? %>
  </div>
</div>

  <br>
  
  <div class="show-big-items">
    <div class="show-big-items-links">
      <strong>Address:</strong> <%= @property.address %>
      <p><strong>Price:</strong> $ <%= @property.price %></p>
    </div>
    <div class="show-big-items-links">
      <strong>Name</strong> <p><%= @property.name %></p>
      <strong>Rooms</strong><p><i class="fa fa-bed"> <%= @property.rooms %></i></p>
      <strong>Bathrooms</strong><p><i class="fa fa-bath"> <%= @property.bathrooms %></i> </p>
      <strong>Parking spaces</strong><p><i class="fa fa-car"></i> <%= @property.parking_spaces %> </p>
      <p><%= link_to 'Edit', edit_property_path(@property), class:"btn btn-dark"%></p>
      <p><%= link_to 'Destroy', @property, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></p> 
    </div>
  
  
  <div class="Show-big-second">
    <h5>Dave</h5>
    <p>test company</p>
    <button class="btn btn-primary">CALL</button>
    <button class="btn btn-success">EMAIL</button>
  </div>

</div>

<div class="show-description">
  <hr>

  <div class="questions">
  <p>Est. Monthly Repayments of $3,000 </p>
  <p>Est. Monthly Repayments of $3,000 </p>
  </div>
  <hr>

  <div class="villa">
    <h1>Villa Bonita</h1>
    <h6>property discriptions</h6>
     <%= simple_format @property.details %>
    </div>
  <button id="toggleDetails">show more</button>
</div>

app/views/shots/_form.html.erb
<%= simple_form_for @shot, html: { multipart: true } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
  
    <div id="drop_zone">drag and drop here</div>
      <%= f.input :user_kra, label: 'Upload file' %>
      <%= f.input :title %>
      <%= f.input :description %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class:"btn btn-default" %>
    </div>
<% end %>

app/views/shots/edit.html.erb
<h1>Editing Shot</h1>

<%= render 'form', shot: @shot %>

<%= link_to 'Show', @shot %> |
<%= link_to 'Back', shots_path %>

app/views/shots/index.html.erb
<div class="container">
    <div id="indexleft" class="centerme">
        <div  class="row">        
            <% @shots.each do |shot| %>
                <div class="col-sm, float-sm-left">
                    <div class="index">
                        <%= link_to image_tag(shot.user_kra.url (:thumb)), shot %>
                        <%= shot.title %>
                        <button type="button" class="btn btn-light"><%= link_to root_path(@shot) do %>
                            <span class="glyphicon glyphicon-eye-open"></span> 
                            <%end%>
                        </button>         
                    </div>
                </div>
            <% end %>
        </div>
    </div> 
</div>

           
            


           
    

app/views/shots/new.html.erb
<div class="container">
    <div class="newshot">
        <h3>What are you working on?</h3>   
        <div id= "mm" class="row">
            <div class ="col-12">
                <%= render 'form', shot: @shot %>
            </div>
        </div>
    </div>
</div>

app/views/shots/show.html.erb
 
  



  



<div id ="showblack" class="container">

  <h3>Netflix UI Concept</h3>
  <p>Posted by: <%= current_user.name.capitalize%>  <%= time_ago_in_words(@shot.created_at)%> ago</p>
    
  <div class="showpadding">

    <div class="show">
      <div class="row">
        <div class="col-4">
          <%= image_tag @shot.user_kra_url (:full) unless @shot.user_kra.blank? %>
        </div>
      </div>
    </div>

      <div class="showbutt">
        <%= link_to "Edit", edit_shot_path(@shot), class:"btn btn-basic" %>
         <%= link_to "Delete", shot_path(@shot), method: :delete, data:{confirm: "Are you sure?"}, class: 'btn btn-basic' %>
      </div>
      <div class="showdetails">
        <h3><%= @shot.title %></h3>
        <p><%= @shot.description %></p>
      </div>
      
      <h5 class="count"><%= pluralize(@shot.comments.count, "comments")%></h5>

      <%= render @shot.comments %>

      <div class="comments">

        <% if user_signed_in? %>
        <%= render "comments/form" %>
        <% else %>
        <%= link_to "Sign in", new_user_session_path, class:"btn btn-success" %>
        <% end %> 
    
      </div>
      
  </div>

</div>


  
<table class="showfloat">
<tr>
  <th class="glyphicon glyphicon-eye-open"> 0 Views </th>
</tr>
<tr>
  <th class="glyphicon glyphicon-comment"> 0 </th>
 
</tr>
<tr>
  <th class="glyphicon glyphicon-heart"> 0 </th>
  
</tr>

</table>